name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: "install choosenim"
        run: curl -OL https://github.com/dom96/choosenim/releases/download/v0.6.0/choosenim-0.6.0_windows_amd64_debug.exe

      - name: "install nim"
        run: .\choosenim-0.6.0_windows_amd64_debug.exe -y devel

      - name: "setup path"
        run: ::add-path::"%homepath%/.nimble/bin

      - name: "show version"
        run: %homepath%/.nimble/bin/nim -v

      - name: "show version 2"
        run: nim -v
