name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019

    steps:
    - run: curl -OL https://github.com/dom96/choosenim/releases/download/v0.6.0/choosenim-0.6.0_windows_amd64_debug.exe
    - run: .\choosenim-0.6.0_windows_amd64_debug.exe devel
    - run: nim -v
